src/Entity/Choix.php
<?php

namespace App\Entity;

use App\Repository\ChoixRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ChoixRepository::class)]
class Choix
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?int $pv_perdus = null;

    #[ORM\Column(nullable: true)]
    private ?int $pv_gagnes = null;

    #[ORM\Column(nullable: true)]
    private ?int $endurance = null;

    #[ORM\Column(nullable: true)]
    private ?int $puissance = null;

    #[ORM\Column(nullable: true)]
    private ?int $intelligence = null;

    #[ORM\Column(nullable: true)]
    private ?int $esquive = null;

    #[ORM\ManyToOne(inversedBy: 'choix')]
    private ?Scenario $scenario = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPvPerdus(): ?int
    {
        return $this->pv_perdus;
    }

    public function setPvPerdus(?int $pv_perdus): static
    {
        $this->pv_perdus = $pv_perdus;

        return $this;
    }

    public function getPvGagnes(): ?int
    {
        return $this->pv_gagnes;
    }

    public function setPvGagnes(?int $pv_gagnes): static
    {
        $this->pv_gagnes = $pv_gagnes;

        return $this;
    }

    public function getEndurance(): ?int
    {
        return $this->endurance;
    }

    public function setEndurance(?int $endurance): static
    {
        $this->endurance = $endurance;

        return $this;
    }

    public function getPuissance(): ?int
    {
        return $this->puissance;
    }

    public function setPuissance(?int $puissance): static
    {
        $this->puissance = $puissance;

        return $this;
    }

    public function getIntelligence(): ?int
    {
        return $this->intelligence;
    }

    public function setIntelligence(?int $intelligence): static
    {
        $this->intelligence = $intelligence;

        return $this;
    }

    public function getEsquive(): ?int
    {
        return $this->esquive;
    }

    public function setEsquive(?int $esquive): static
    {
        $this->esquive = $esquive;

        return $this;
    }

    public function getScenario(): ?Scenario
    {
        return $this->scenario;
    }

    public function setScenario(?Scenario $scenario): static
    {
        $this->scenario = $scenario;

        return $this;
    }

    public function __toString(): string
    {
        return $this->nom;
    }
}

src/Form/ChoixType.php
<?php

namespace App\Form;

use App\Entity\Choix;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChoixType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('description')
            ->add('pv_perdus')
            ->add('pv_gagnes')
            ->add('endurance')
            ->add('puissance')
            ->add('intelligence')
            ->add('esquive')
            ->add('scenario')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Choix::class,
        ]);
    }
}

src/Controller/ChoixController.php
<?php

namespace App\Controller;

use App\Entity\Choix;
use App\Form\ChoixType;
use App\Repository\ChoixRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ChoixController extends AbstractController
{
    #[Route('/admin/choix', name: 'app_choix_index', methods: ['GET'])]
    public function index(ChoixRepository $choixRepository): Response
    {
        return $this->render('choix/index.html.twig', [
            'choixes' => $choixRepository->findAll(),
        ]);
    }

    #[Route('/admin/choix/new', name: 'app_choix_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $choix = new Choix();
        $form = $this->createForm(ChoixType::class, $choix);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($choix);
            $entityManager->flush();

            return $this->redirectToRoute('app_choix_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('choix/new.html.twig', [
            'choix' => $choix,
            'form' => $form,
        ]);
    }

    #[Route('/admin/choix/{id}', name: 'app_choix_show', methods: ['GET'])]
    public function show(Choix $choix): Response
    {
        return $this->render('choix/show.html.twig', [
            'choix' => $choix,
        ]);
    }

    #[Route('/admin/choix/edit/{id}', name: 'app_choix_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Choix $choix, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ChoixType::class, $choix);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_choix_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('choix/edit.html.twig', [
            'choix' => $choix,
            'form' => $form,
        ]);
    }

    #[Route('/admin/choix/{id}', name: 'app_choix_delete', methods: ['POST'])]
    public function delete(Request $request, Choix $choix, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$choix->getId(), $request->request->get('_token'))) {
            $entityManager->remove($choix);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_choix_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/choix/_delete_form.html.twig
<form method="post" action="{{ path('app_choix_delete', {'id': choix.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer ce choix ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ choix.id) }}">
    <button class="create-button">Supprimer</button>
</form>

templates/choix/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Créer') }}</button>
{{ form_end(form) }}
<style>
    form {
        max-width: 400px;
        margin: 0 auto;
        background-color: #f4f4f4;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
</style>

templates/choix/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Space Unicorn Admin{% endblock %}

{% block body %}
{{ include('admin/_header.html.twig') }}

    <h1 class="choix__titre">Edit Choix</h1>
    {{ include('choix/_form.html.twig', {'button_label': 'Modifier'}) }}
    <div style="width:100%; justify-content:center; display:flex; margin-top: 20px;">
        <a class="create-button" href="{{ path('app_choix_index') }}">Retour à la liste</a>
    </div>
{% endblock %}

templates/choix/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Space Unicorn Admin{% endblock %}

{% block body %}
{{ include('admin/_header.html.twig') }}

    <h1 class="choix__titre">Choix</h1>
    <div style="width:100%;justify-content:center;display:flex;padding-bottom:20px;">
        <a href="{{ path('app_choix_new') }}" class="create-button">Créer un choix</a>
    </div>
    <table class="table table-success table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Description</th>
                <th>Pv_perdus</th>
                <th>Pv_gagnes</th>
                <th>Endurance</th>
                <th>Puissance</th>
                <th>Intelligence</th>
                <th>Esquive</th>
                <th>Scenario</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for choix in choixes %}
            <tr>
                <td>{{ choix.id }}</td>
                <td>{{ choix.nom }}</td>
                <td>{{ choix.description }}</td>
                <td>{{ choix.pvPerdus }}</td>
                <td>{{ choix.pvGagnes }}</td>
                <td>{{ choix.endurance }}</td>
                <td>{{ choix.puissance }}</td>
                <td>{{ choix.intelligence }}</td>
                <td>{{ choix.esquive }}</td>
                <td>{{ choix.scenario }}</td>
                <td>
                    <a href="{{ path('app_choix_show', {'id': choix.id}) }}" class="create-button">Voir</a>
                    <a href="{{ path('app_choix_edit', {'id': choix.id}) }}" class="create-button">Modifier</a>
                    {{ include('choix/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/choix/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Space Unicorn Admin{% endblock %}

{% block body %}
{{ include('admin/_header.html.twig') }}

    <h1 class="choix__titre">Créer un choix</h1>

    {{ include('choix/_form.html.twig') }}
    <div style="width:100%; justify-content:center; display:flex; margin-top: 20px;">
        <a class="create-button" href="{{ path('app_choix_index') }}">Retour à la liste</a>
    </div>
{% endblock %}

templates/choix/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Space Unicorn Admin{% endblock %}

{% block body %}
{{ include('admin/_header.html.twig') }}

    <h1 class="choix__titre">Choix</h1>

    <table class="table table-success table-striped">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ choix.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ choix.nom }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ choix.description }}</td>
            </tr>
            <tr>
                <th>Pv_perdus</th>
                <td>{{ choix.pvPerdus }}</td>
            </tr>
            <tr>
                <th>Pv_gagnes</th>
                <td>{{ choix.pvGagnes }}</td>
            </tr>
            <tr>
                <th>Endurance</th>
                <td>{{ choix.endurance }}</td>
            </tr>
            <tr>
                <th>Puissance</th>
                <td>{{ choix.puissance }}</td>
            </tr>
            <tr>
                <th>Intelligence</th>
                <td>{{ choix.intelligence }}</td>
            </tr>
            <tr>
                <th>Esquive</th>
                <td>{{ choix.esquive }}</td>
            </tr>
        </tbody>
    </table>
    <div style="width:100%; justify-content:center; display:flex; margin-top: 20px;">
    <a class="create-button" href="{{ path('app_choix_index') }}" style="margin-right:10px;">Retour à la liste</a>
    <a class="create-button" href="{{ path('app_choix_edit', {'id': choix.id}) }}" style="margin-right:10px;">Modifier</a>
    {{ include('choix/_delete_form.html.twig') }}
    </div>
{% endblock %}